[package]
name = "doulets-vs-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
doublets = { path = "../../LinksPlatform/Data.Doublets/rust" }
num-traits = "0.2.14"
rand = "*"
chrono = "0.4.19"
cached = "0.26.2"